# Generated by Django 6.0.3 on 2026-03-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='day_2/media/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='day_2/media/images/%Y/%m/%d'),
        ),
    ]
